generation_output_dir: ...
gt_json_file: ${hydra:runtime.cwd}/RESULTS/midjv6_gt/annotations.json
gt_images_folder: ${hydra:runtime.cwd}/RESULTS/midjv6_gt/images

hydra:
  run:
    dir: ${generation_output_dir}
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        level: DEBUG
        filename: ${generation_output_dir}/image_fid_score_evaluation.log
    root:
      level: DEBUG
      handlers: [file, console]
