output_dir: "lcm-xl-distilled"
cache_dir: "./tmp/cache"
seed: 42
checkpointing_steps: 500
checkpoints_total_limit: 2
resume_from_checkpoint: latest
logging_dir: "logs"
report_to: "wandb"
push_to_hub: false
hub_token: null
hub_model_id: null
tracker_project_name: "accediff"