_target_: accediff.utils.factory.pipeline_factory.get_cogvideox_pipeline_with_tome
repo_id: "THUDM/CogVideoX-2b"
tome_modele_names:


  # # this slighly improves the output quality
  # # tome all
  # - transformer_blocks.{0..27}.attn1
  
  # tome 14 layers
  - transformer_blocks.{0..27..2}.attn1 # destory the low frequency information
  
  # tome mid 20 layers
  # - transformer_blocks.{0..10}.attn1
  # - transformer_blocks.{17..27}.attn1

  # tome 15 layers
  # - transformer_blocks.{12..27}.attn1 # destory the high frequency information
  # - transformer_blocks.{0..15}.attn1 # destory the low frequency information


  # - transformer_blocks.{4..24}.attn1 # not working
  # - attn1
  # - ff # don't do this, this caused low quality high cost
  # - transformer_blocks.{0..10}.attn1
  # - transformer_blocks.{20..27}.attn1
  # - transformer_blocks.{0..10}.ff
  # - transformer_blocks.{20..27}.ff
  # - transformer_blocks.{10..20}.attn1
  # - transformer_blocks.{10..20}.ff